version: '3'

services:
  source_db:
    image: postgres:16
    container_name: source_db
    restart: always
    environment:
      - POSTGRES_DB=paccafe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminadmin
    ports:
      - 5435:5432
    volumes:
      - ./source_data:/docker-entrypoint-initdb.d
      - source-volume:/var/lib/postgresql/data

volumes:
  source-volume:
